# Blog info
blog_name: Jeremy'Memo
slogan: Be 哈比 ヾ(❀╹◡╹)ﾉ~
url: http://www.alzz.me

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.png

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: android,mac,ubuntu,Hexo主题,linux

home_nav:
  - name: Articles
    url: /archives
    target_blank: false #不在新页面打开
  - name: Category
    url: /category/
    target_blank: false #在新页面打开
  #- name: Project
    #url: /project/
    #target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/JeremyHe-cn
    target_blank: true

# config page nav
page_nav:
  - name: 文章
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: ""

search_slogan:
  isShow: true # true|fase
  text: What u want ?

link_slogan:
  isShow: false # true|fase
  text: 交换友链可以邮件 jeremyhe.cn@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 一起 Coding ???
  tip: 严于己，宽于人｡◕‿◕｡
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    #- type: 支付宝
      #text: 支付宝扫一扫
      #imgUrl: /images/qr-alipay.png


post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
#blog_name_font_familiy: calligraffittiregular
#blog_name_font_familiy: Lobster-Regular
blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:

# Comment service
# disqus_shortname: jeremyhe
# hypercomments_id: 89821
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# Valine comment system  https://valine.js.org
valine:
  enable: true # 如果使用valine，请设置改之为true
  appid: FkkXjkB8RmuNQxEhqk6BM3Ww-gzGzoHsz # your leancloud application appid
  appkey: ReNBuhWx88Con7IipJ5tLg79 # your leancloud application appkey
  notify: true # mail notifier , https://github.com/xCss/Valine/wiki
  verify: true # Verification code
  placeholder: 'ヾﾉ≧∀≦)o来啊，快活啊!' # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "JeremyHe (AL)，Android Developer, Vimer."
    - "在创造的路上越走越深。"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@JeremyHe"
    text_value_url: https://github.com/JeremyHe-cn
  #- type: weibo
    #icon: icon-weibo
    #text_key: 微博
    #text_value: "@forsigner"
    #text_value_url: http://weibo.com/u/1847075964
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "JeremyHe.cn@gmail.com"
  - type: location
    icon: icon-location
    text_value: 深圳

#link:
  #- name: 织网
    #info: 身体和灵魂，总有一个在路上
    #url: http://zheng-ji.info/
    #avatar: https://avatars3.githubusercontent.com/u/1414745?v=3&s=100

#project:
  #- type: personal
    #name: fexo
    #url: https://github.com/forsigner/fexo
    #intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
